
#ifndef complex_lib_docstrings_hpp
#define complex_lib_docstrings_hpp

#include <string>

// Test docstrings.
// Doxygen breifdoc comments are extracted from the
// source code and included in autogenerated documentation.

namespace ComplexLib {

    // class Doc1 and function docFunc1 are documented
    // with Doxygen style comments.

    class Doc1 {
    public:
        //! Construct an object of type Doc1
        Doc1() {}
        //! Add two numbers together
        long sum(
            long a,  //!< The first number to be summed
            long b   //!< The second number to be summed
        ) const;
    };

    //! Echo input string to stdout
    void docFunc1(
        const std::string &s    //!< The string to be echoed
    );

    // class Doc2 and function docFunc2 are documented
    // in the SWIG interface file.  Any docstrings provided here
    // will be overwritten.
    class Doc2 {
    public:
        //! This docstring will be overwritten
        Doc2() {}
        long sum(
            long a,
            long b) const;
    };

    void docFunc2(const std::string &s);
};

#endif

